name: ChatPolice
version: '1.0'
main: me.skygamez.chatpolice.ChatPolice
api-version: "1.20"
authors: [SkyGameZ]
description: Provides better control over your servers chat
commands:
  chatpolice:
    description: chatpolice
  clearchat:
    description: clearchat
  chatlockdown:
    description: chatlockdown
